# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Use zen kernel for gaming performance
  boot.kernelPackages = pkgs.linuxPackages_zen;
  powerManagement.cpuFreqGovernor = "performance";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/20f7ca12-f585-4d3a-b6d9-304b46ab9b12";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3EA7-915C";
      fsType = "vfat";
    };

  swapDevices =
    [  { device = "/dev/disk/by-uuid/49720451-caa2-467f-9053-ee55b96cc029"; }
    ];

}
