#!/usr/bin/env bash

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

# 5 workspaces for primary monitor, 2 for secondary monitor
bspc monitor $MONITOR -d {1,2,3,4,5}
[[ $(echo $MONITORS | cut -d' ' -f2) ]] && bspc monitor $(echo "$MONITORS" | cut -d' ' -f2) -d {9,10}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


# Rules
bspc rule -r '*'

bspc rule -a Pinentry state=floating center=on
bspc rule -a Emacs split_ratio=0.72 split_dir=west state=tiled
bspc rule -a Firefox split_ratio=0.32
bspc rule -a feh state=fullscreen
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a 'Emacs:emacs-everywhere' state=floating sticky=on
bspc rule -a '*:scratch' state=floating sticky=on center=on border=off rectangle=1000x800+0+0

# load stuff configured elsewhere e.g. theme
for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
