#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# Start workspaces on the main monitor.
if xrandr --listactivemonitors | grep HDMI-0 >/dev/null; then
	bspc monitor DVI-I-1 -d 1 2 3 4 5 6 7 8
	bspc monitor HDMI-0 -d 9 10
	bspc desktop -f 1
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
	bspc desktop -f 1
fi

bspc config border_width 2
bspc config focused_border_color "#51afef"
bspc config window_gap 10
bspc config top_padding 18
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled
bspc rule -a Thunar state=floating
